import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import Container from "./Container";
import ClientNavbar2 from "../_components/ClientNavbar2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface ClientDashboardLayoutProps {
  children: React.ReactNode;
}

export default function ClientDashboardLayout({
  children
}: ClientDashboardLayoutProps) {

  return (
    <div className="bg-muted/40">
      <ClientNavbar2 />
      <Container>
        <div className="mt-6">{children}</div>
      </Container>
    </div>
  );
}
