import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import VendorProjectDashboardContainer from "./VendorProjectDashboardContainer";
import { User } from "@supabase/supabase-js";
import { GetCurrentUser } from "@/components/actions/users/UserActions";
import { GetProjectById } from "@/components/actions/projects/ProjectActions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface VendorDashboardLayoutProps {
  children: React.ReactNode;
}

export default async function VendorDashboardLayout({
  children
}: VendorDashboardLayoutProps) {

  const user: User | null = await GetCurrentUser();
  if (!user) {
    throw "[LAYOUT] wtf this should not get here...";
  }
  
  return (
    <div lang="en">
      <VendorProjectDashboardContainer>
        {children}
      </VendorProjectDashboardContainer>
    </div>
  );
}
