import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../../globals.css";
import ClientProjectDashboardContainer from "./ClientProjectDashboardContainer";
import { User } from "@supabase/supabase-js";
import { GetCurrentUser } from "@/components/actions/users/UserActions";
import { GetProjectById } from "@/components/actions/projects/ProjectActions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface ClientDashboardLayoutProps {
  children: React.ReactNode;
  params: {
    projectId: string;
  };
}

export default async function ClientDashboardLayout({
  children,
  params,
}: ClientDashboardLayoutProps) {

  const user: User | null = await GetCurrentUser();
  if (!user) {
    throw "[LAYOUT] wtf this should not get here...";
  }

  const { projectId } = params;

  const project = await GetProjectById(Number(projectId));
  if (!project) {
    throw "[ClientDashboardLayout] project not found";
  }
  
  return (
    <div lang="en">
      <ClientProjectDashboardContainer project={project}>
        {children}
      </ClientProjectDashboardContainer>
    </div>
  );
}
